INSERT INTO dbo.CategoryEntity VALUES ('Front-End Development', '06-24-2022', '06-24-2022');
INSERT INTO dbo.CategoryEntity VALUES ('Design', '06-24-2022', '06-24-2022');

INSERT INTO dbo.ClientEntity VALUES ('Client 1', 'Cara Dusana 6', 'Novi Sad', 11000, 'Serbia', '06-28-2022', '06-28-2022');
INSERT INTO dbo.ClientEntity VALUES ('Client 2', 'Novosadskog sajma 2', 'Novi Sad', 11000, 'Serbia', '06-28-2022', '06-28-2022');